#!/bin/sh

mkdir ${HOME}/.ssh
chmod 700 ${HOME}/.ssh
touch ${HOME}/.ssh/known_hosts
chmod 600 ${HOME}/.ssh/known_hosts
ssh-keyscan github.com > ~/.ssh/known_hosts
mkdir -p tmp/pids
bundle install --jobs 4 --deployment --no-cache --without development deploy
bundle clean --force
rm -fr /cache/bundle/ruby/2.2.0/cache
RAILS_ENV=production bundle exec rake assets:precompile tmp:clear
chown -R app:app /build
